server:
  port: 80

logging:
  level:
    org:
      springboot:
        security: info
        info: info
    '[com.gemeshop.mapper]': trace

mybatis:
  mapper-locations:
    - mybatis/mapper/*.xml
  type-aliases-package: com.gameshop.vo
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

spring:
  # ??? ? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: zxcv1234