server:
  port: 80

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      springboot:
        security: info
        info: info
    '[com.gemetruck.mapper]': trace

spring:
  profiles:
    include:
      - dev
      - auth

mybatis:
  mapper-locations:
    - mybatis/mapper/*.xml
  type-aliases-package: com.gametruck.vo
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
